name: Passing variables across jobs
on:
  workflow_dispatch:

jobs:
  producer:
    runs-on: ubuntu-24.04

    outputs:
      foo: ${{ steps.generate-foo.outputs.foo }}
    steps:
      - name: define and export foo
        id: generate-foo

        run: |
          foo=bar

          echo "foo=${foo}" >> "$GITHUB_OUTPUT"
          echo "FOO=${foo}" >> "$GITHUB_ENV"
    
      - name: Inspect valud inside producer
        run: |
          echo "FOO (set via github env): $FOO"
          echo "foo (step output): ${{ steps.generate-foo.outputs.foo }}"
    
  consumer:
    runs-on: ubuntu-24.04
    needs: producer
    steps:
      - name: Inspect values inside consumer
        run: |
          echo "foo (step output): ${{ needs.producer.outputs.foo }}"
          echo "FOO (set via github env): ${FOO:-NOPE}"
